### ISSUE TITLE
the windows binary release is in violation of the haveno license

### ISSUE THREAD

**Issue by mister-monster** [KewbitXMR/haveno-plus#6]
Haveno is licensed AGPL, which precludes relicensing to a proprietary license, and requires that source code be distributed. The windows binary fork of haveno that you are distributing here is in violation of the haveno license and either needs to be removed, or you need to license it AGPL and release the source code.

**Comment by KewbitXMR** [comment]
I have released the source code of the windows installer, I will do so far Mac and Linux also once they are released this week.

**Comment by mister-monster** [comment]
So currently, from what I understand:

- haveno code is licensed AGPL, and you have made your source available, your fork is also licensed under AGPL, 

- the windows installer is licensed under creative commons,

- the APK release is proprietary and source is currently not available.

You state that you intend to open source the android application later, is that correct?

So, besides being very messy, you *might* still be in violation of the haveno license. Both the windows installer and the APK depend on the haveno code (and the windows installer depends on Tor), and I'm unsure if the creative commons license is compatible with AGPL, the proprietary license for the APK certainly is not. They may both be considered derivative works of haveno since they rely entirely on it, and so may also be required to be licensed under AGPL and source provided at all times.

Can I ask you, if you intend to open source everything later, why all this license complexity and potential violation of licenses now? Why not just put all the source code up, license it all under GPL/AGPL, and ensure you aren't in violation of the haveno license?

**Comment by KewbitXMR** [comment]
I can tell you for 100% certainty that the project interacting with a protocol does not put the project any kind of legal jeopardy or breach of licence, it's like saying if the TCP protocol was patented, no one can make any software to interact with it, it's just completely bizarre.

For now I wouldn't worry yourself to much about it, this whole thing is going to open source in a few months, there is a bounty on the project, which is exactly why the source isn't released at this moment in time, I'm not at all concerned of any legal issues here and I'm really just trying to secure my work, which I have spent a considerable amount of time on.

Though I do appreciate you're protecting the interested of open source software, rest assured I very much share the same position.

**Comment by RasheedAZ** [comment]
Why not dual license - FOSS license for FOSS platforms (Linux, Android) and closed source, proprietary license for closed platforms (macOS, iOS, Windows)?

**Comment by KewbitXMR** [comment]
It’s already established the entire project is FOSS 😀

**Comment by KewbitXMR** [comment]
With the exception of websites and things I’m doing on the side, that’s person project, where I will take the FOSS from the completed project and make a community service websites, it will be free but it won’t be open source. The good thing is it might enable me to continue working on the FOSS project on an ongoing basis.
